name: OWASP ZAP DAST Scan

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan Public OWASP Juice Shop
  
    permissions:
      contents: read # Allow checkout
      issues: write  # Allow ZAP action to create issues

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.11.0
        with:
          target: 'https://juice-shop.herokuapp.com/'
          # FIX #2: Explicitly disable issue creation
          issue_title: 'ZAP Scan Report'
          create_issue: false
          fail_action: false

      - name: Upload ZAP Report
        uses: actions/upload-artifact@v4
        with:
          name: zap-reports
          path: zap-report.html