name: OWASP ZAP DAST Scan

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan Public OWASP Juice Shop

    steps:
      # Step 1: Check out the code
      - name: Checkout
        uses: actions/checkout@v4

      # Step 2: Run ZAP directly using Docker (bypassing the problematic action)
      - name: Run ZAP Baseline Scan
        run: |
          docker run --rm \
            -v $(pwd):/zap/wrk/:rw \
            -t ghcr.io/zaproxy/zaproxy:stable \
            zap-baseline.py \
            -t https://juice-shop.herokuapp.com/ \
            -J zap-report.json \
            -w zap-report.md \
            -r zap-report.html

      # Step 3: Upload ZAP reports
      - name: Upload ZAP Reports
        uses: actions/upload-artifact@v4
        with:
          name: zap-security-reports
          path: |
            zap-report.html
            zap-report.json
            zap-report.md
          retention-days: 30